# Generated by Django 3.2.7 on 2021-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('company_name', models.CharField(max_length=128)),
            ],
        ),
    ]
