# Generated by Django 3.2.7 on 2021-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default='Out of Stock', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://bitsofco.de/content/images/2018/12/broken-1.png', max_length=5000),
        ),
    ]
