# Generated by Django 3.2.7 on 2021-11-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211113_1029'),
        ('shopapp', '0005_auto_20211103_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Retailer_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.retailer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Status',
            field=models.CharField(default='Ordered', max_length=128),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('user', models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
