# Generated by Django 3.2.7 on 2021-10-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20211025_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
