# Generated by Django 3.2.7 on 2021-11-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20211113_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
    ]
