# Generated by Django 3.2.7 on 2021-10-25 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_cart_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
