# Generated by Django 3.2.7 on 2021-10-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_cartitem_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.in%2FApsara-Absolute-Premium-Pencils-Sharpner%2Fdp%2FB0844PKQXY&psig=AOvVaw2qNLmyGyerVX4sMstC-ugD&ust=1635315172739000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCICXhfO15_MCFQAAAAAdAAAAABAD'),
        ),
    ]
