# Generated by Django 3.2.7 on 2021-10-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://m.media-amazon.com/images/I/71mCWONL67L._SL1500_.jpg', max_length=5000),
        ),
    ]
