# Generated by Django 3.2.7 on 2021-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_auto_20211026_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
    ]
