# Generated by Django 3.2.7 on 2021-10-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
