# Generated by Django 3.2.7 on 2021-10-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_retailer'),
        ('shopapp', '0016_remove_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
