# Generated by Django 3.2.7 on 2021-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.TextField()),
                ('gstNo', models.TextField(unique=True)),
                ('whyyou', models.TextField()),
                ('Products', models.TextField()),
            ],
        ),
    ]
