# Generated by Django 3.2.7 on 2021-11-01 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='id',
        ),
        migrations.AddField(
            model_name='retailer',
            name='Retailer_ID',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
