# Generated by Django 3.2.7 on 2021-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211101_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='Retailer_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
