# Generated by Django 3.2.7 on 2021-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_retailer_retailer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='retailer',
            name='city',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='retailer',
            name='phone',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='retailer',
            name='state',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='hostel',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
